using System;
using System.Collections.Generic;

namespace HowToLua;

internal sealed class GameEventQueue
{
    private readonly Queue<(string Name, object[] Args)> _queue = new();
    internal bool Add(string name, object[] args)
    {
        if (_queue.Count >= 1024) return false;
        _queue.Enqueue((name, args));
        return true;
    }
    internal void Clear() => _queue.Clear();
    internal void Drain(Action<string, object[]> dispatch)
    {
        // Events generated by callbacks stay queued until the next Update.
        int count = Math.Min(128, _queue.Count);
        while (count-- > 0 && _queue.Count > 0)
        {
            var next = _queue.Dequeue();
            dispatch(next.Name, next.Args);
        }
    }
}
